version: '3.8'
services:
  db:
    image: postgis/postgis:15-3.4
    environment:
      - POSTGRES_USER=canopy
      - POSTGRES_PASSWORD=canopy
      - POSTGRES_DB=canopy_db
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data:
